# FILE NAMES

# 1. Business Feasibility Studies & Project Reports (Sector-Specific)
manufacturing_ventures = ['3D Cinema Rs. 20.55 million Dec-2020.pdf','Advanced Oncology Center Blood Cancer Hospital Rs. 368 million Jun-2022.pdf','Agricultural Implements Manufacturing Unit Rs. 17.89 million Nov-2023.pdf','Air Bubble Packing Sheet Manufacturing Unit Rs. 9.96 million Jan-2021.pdf','Aloe Vera Processing Unit Rs. 190.40 million Nov-2023.pdf','Apple Treatment Plant Rs. 102.46 million Dec-2023.pdf','Artificial Rubber Tiles Manufacturing Plant Rs. 13.14 million Jan-2021.pdf','Bed Linen Stitching Unit Rs. 26.97 million Sep-2023.pdf','Bio-Degradable Plastic Bags Manufacturing Unit Rs. 5.81 million Feb-2021.pdf','Blow Molding Plastic Products Rs. 11.26 million Jun-2021.pdf','Bread Rusk And Biscuit Manufacturing Unit Rs. 7.94 million Dec-2020.pdf','Calcium Carbonate Production Unit Rs. 62.19 million Jun-2020.pdf','Candle Manufactring Unit Rs. 20.60 million Dec-2024.pdf','Canola and Soybean Oil Refining Packaging Unit Rs. 85.88 million Dec-2022.pdf','Ceramic Tiles Production Plant Rs. 116.31 million Jun-2020.pdf','China Clay Processing Plant Rs. 127.97 million Dec-2023.pdf','Chipboard Manufacturing Plant Rs. 701.12 million Feb-2021.pdf','Cigarette Lighter Manufacturing Unit Rs. 4.78 million May-2021.pdf','Clay Bricks Manufactruing Kiln Zigzag Technology Rs. 33.74 million Jun-2021.pdf','Coal Washing Plant Rs. 70.56 million Dec-2023.pdf','Cotton Towel Manufacturing Unit Rs. 306.47 million Feb-2021.pdf','Crockery Manufacturing Unit Rs. 22.62 million Jan-2023.pdf','Dates Paste Manufactring Unit Rs. 2.91 million Mar-2023.pdf','Detergent Powder Manufacturing Unit Rs. 28.83 million Jun-2021.pdf','Diapers Manufacturing Unit Rs. 116.59 million Feb-2021.pdf','Dish Wash Liquid Soap Bar Manufacturing Unit Rs. 43.17 million May-2021.pdf','Electric Telephone Other Copper-based Cables Manufacturing Unit Rs. 13.54 million April-2021.pdf','Electric Bicycle Manufacturing Unit Rs. 5.93 million Mar-2021.pdf','Fiber Glass Products Manufacturing Unit Rs. 23.43 million Dec-2023.pdf','Fiberglass Boat Manufacturing Unit Rs. 55.77 million May-2021.pdf','Floor Cleaner Manufacturing Unit Rs. 25.09 million Feb-2021.pdf','Flour Mill Rs. 270.75 million Sep-2023.pdf','Fluorite Mining Rs. 105.16 million Dec-2023.pdf','Fruit Jam - Jelly Marmalade Production Rs. 9.96 million Dec-2020.pdf','Fruit Juice Manufacturing Unit Rs. 26.85 million Jan-2020.pdf','Garlic Powder and Paste Production Unit Rs. 400.41 million Dec-2023.pdf','Glass Manufacturing Unit Rs. 713.70 million May-2021.pdf','Gravure Printing Unit Rs. 505.08 million Jun-2021.pdf','Ground Calcium Carbonate Mill Rs. 93.04 million Jan-2024.pdf','Hard Gelatin Capsule Shell Manufacturing Unit Rs. 95.92 million Jun-2021.pdf','HDPE Sheets Manufacturing Unit Rs. 38.59 million Sep-2024.pdf','Heat Sublimation Printing Unit Rs. 5.59 million Nov-2020.pdf','Herbal Cosmetics Manufacturing Unit Rs. 69.08 million Jun-2021.pdf','High Pressure Die-Casting Manufacturing Unit Rs. 75.35 million Oct-2022.pdf','High-Density Polyethylene HDPE Pipes Production Unit Rs. 41.05 million Dec-2022.pdf','Hosiery Knitwear Unit Rs. 64.20 million Dec-2022.pdf','Household Sewing Machine Manufacturing Unit Rs. 6.53 million Oct-2022.pdf','Injection Molding Plastic Products Rs. 27.11 million Jun-2022.pdf','Kitchen Utensils Manufacturing Unit Rs. 62.75 million Apr-2021.pdf','Kraft and Fluted Paper Manufacturing Unit Rs. 251.77 million May-2021.pdf','LED Light Bulb Restoration Hub Rs. 3.74 million Sep-2024.pdf','Light Weight Roof Tiles Manufacturing Unit Rs. 4.31 million Jun-2022.pdf','Limestone Processing Unit Rs. 33.09 million Jun-2022.pdf','Liquid Hand Wash Rs. 5.06 million Mar-2020.pdf','Manufacturing of Aluminum Food Packaging Containers Rs. 12.93 million Aug-2022.pdf','Manufacturing Unit for Bolts Nuts Screws Rivets and Washers Rs. 32.67 million Nov-2021.pdf','Manufacturing Unit for Electric Motors Rs. 22.55 million Oct-2022.pdf','Manufacturing Unit for Electrical Distribution Boxes Rs. 15.24 million Dec-2022.pdf','Manufacturing Unit for Electronic Capacitors Resistors and Connectors Rs. 34.58 million Nov-2021.pdf','Manufacturing Unit for Fabricated Pipe and Pipe Fittings Rs. 29.95 million Nov-2021.pdf','Manufacturing Unit for Household Laundry Equipment Rs. 58.42 million Nov-2021.pdf','Manufacturing Unit For Household Vacuum Cleaner Rs. 35.26 million Aug-2021.pdf','Manufacturing Unit for Industrial Valves Rs. 18.70 million Nov-2021.pdf','Manufacturing Unit for Office Furniture Rs. 14.28 million Dec-2022.pdf','Manufacturing Unit for Perfume Rs. 24.32 million Oct-2021.pdf','Manufacturing Unit for Primary Batteries Rs. 116.2 million Oct-2021.pdf','Manufacturing Unit for Residential Electric Lighting Fixtures Rs. 21.56 million Nov-2021.pdf','Manufacturing Unit for Room Cooler Rs. 80.46 million Oct-2022.pdf','Manufacturing Unit for Sealant Rs. 29.66 million Nov-2021.pdf','Manufacturing Unit for Steel Wire Spring Rs. 52.75 million Nov-2021.pdf','Manufacturing Unit for Varnishes and Lacquers Rs. 13.42 million Oct-2021.pdf','Manufacturing Unit for Water Pumps Rs. 26.83 million Dec-2022.pdf','Manufacturing Unit for Wooden Doors Rs. 10.18 million Aug-2022.pdf','Manufacturing Unit of Lake Salt Rs. 20.44 million Nov-2021.pdf','Manufacturing Unit of Prayer Mats Rs. 18.63 million Dec-2022.pdf','Marble Mosaic Manufacturing Unit Rs. 11.20 million Jan-2021.pdf','Marble Processing Plant Rs. 68.68 million Jan-2021.pdf','Melamine Tableware Manufacturing Unit Rs. 16.47 million May-2021.pdf','Metal Injection Molding Technology Rs. 118.46 million Jan-2023.pdf','Mica Processing Unit Rs. 50.09 million Feb-2020.pdf','Mineral Water Bottling Plant 100000 GPD Rs. 235.15 million Jun-2023.pdf','Mineral Water Processing Unit Rs. 5.64 million May-2023.pdf','Mini Flour Mill Rs. 13.87 million Nov-2020.pdf','Motorcycle Chain Manufacturing Unit Rs. 247.13 million Jan-2023.pdf','Motorcycle Safety Helmet Manufacturing Unit Rs. 10.77 million Apr-2021.pdf','N95 and Surgical Mask Stitching Manufacturing Unit Rs. 4.48 million May-2021.pdf','Net Manufacting Unit Rs. 11.25 million Mar-2022.pdf','Non-Woven Bag Manufactring Unit Rs. 30.40 million Sep-2021.pdf','Organic Fertilizer Making Unit Rs. 70.57 million Dec-2022.pdf','Oxygen Gas Producing Plant Rs. 554.24 million Jan-2021.pdf','Packaged Biscuits Manufactring Unit Rs. 19.54 million Jun-2024.pdf','Paper Bag Making Unit Rs. 31.20 million Jun-2020.pdf','Paper Bag Manufacturing Unit Rs. 6.92 million May-2021.pdf','Peanuts Processing Unit Rs. 22.03 million Dec-2020.pdf','PET Preform Manufacturing Unit 19 Liter Bottle Rs. 58.64 million Dec-2021.pdf','Pink Salt Manufacturing and Export Unit Rs. 94.99 million Dec-2023.pdf','Plaster of Paris Plant Rs. 36.96 million Feb-2021.pdf','Plastic Button Manufacturing Rs. 16.03 million Dec - 2020.pdf','Plastic Collapsible Tubes Manufacturing Unit Rs. 79.18 million Feb-2021.pdf','Plastic Crockery Manufacturing Unit Melamine Plastic Rs. 19.01 million Mar-2025.pdf','Plastic Waste Tiles Manufacturing Unit Rs. 58.62 million Feb-2021.pdf','Polypropylene Woven Bags Manufacturing Unit Rs. 295 Million Jun-2022.pdf','Pops Manufactring Unit Rs. 14.89 million Dec-2021.pdf','Pre-Cast Concrete Poles Manufacturing Unit Rs. 229.25 million Mar-2023.pdf','Printing Press Unit Rs. 11.63 million Mar-2024.pdf','Production Unit for Bottled Carbonated Water Rs. 9.26 million Nov-2021.pdf','Production Unit for Candy and Other Confectionery Products Rs. 53.42 million Sep-2021.pdf','Production Unit for Canned Fruits Vegetables Preserves Jams and Jellies Rs. 68.29 million Nov-2023.pdf','Production Unit for Corrugated and Solid Fiber Boxes Rs. 17.44 million Sep-2021.pdf','Production Unit for Dog Food and Cat Food Rs. 14.97 million Nov-2021.pdf','Production Unit for Frozen Food Products Rs. 31.72 million Nov-2021.pdf','Production Unit for Macaroni Spaghetti and Noodles Rs. 8.25 million Sep-2021.pdf','Production Unit for Packaged Popcorn Rs. 41.7 million Sep-2021.pdf','Production Unit for Pancake Syrup Blended and Mixed Rs. 25.73 million Oct-2021.pdf','Production Unit for Printed Circuit Board Rs. 14.68 million Nov-2021.pdf','Production Unit for Salted and Roasted Nuts and Seeds Rs. 11.39 million Nov-2021.pdf','Production Unit of Baking Powder Rs. 4.32 million Nov-2021.pdf','Production Unit of Cereal Breakfast Foods Rs. 27.57 million Sep-2021.pdf','Production Unit of Cider Vinegar Rs. 21.33 million Oct-2021.pdf','Production Unit of Cookies and Crackers Rs. 3.80 million Aug-2021.pdf','Protective Coverall and Medical Masks Manufacturing Unit Rs. 11.83 million Oct-2020.pdf','PVC Membrane for Water Proofing Manufacturing Plant Rs. 80.55 million Jan-2021.pdf','PVC Shrink Sleeves Manufacturing Unit Rs. 16.28 million Jan-2021.pdf','Quartz Powder Ball Mill Rs. 80.43 million Apr-2023.pdf','Raisin Production Unit Rs. 47.85 million Dec-2023.pdf','Red Chilies Dehydration Plant Rs. 30.37 million Jun-2024.pdf','Rice Bran Oil Extraction Unit Rs. 856.45 million Dec-2023.pdf','Rice Glucose Manufacturing Unit Rs. 386.61 million Mar-2023.pdf','Rice Husking Polishing Unit Rs. 105.76 million Feb-2021.pdf','Rice Husking Mill - 26 Tons Rs. 71.46 million Apr 2020.pdf','Rice Mill Processing Unit Rs. 143.58 million Dec-2023.pdf','Rubber Sole Insole Manufacturing Unit Rs. 11.15 million May-2021.pdf','Salt Products Manufacturing Unit Rs. 4.69 million Jan-2022.pdf','Sausage Production Plant Rs. 6.89 million Feb-2021.pdf','Sea Food Processing Plant Rs. 161.03 million Dec-2023.pdf','Skin Care Products Manufacturing Marketing Rs. 11.63 million Jun-2022.pdf','Slaughter House Rs. 237.20 million Feb-2021.pdf','Small Arms Manufacturing Unit Rs. 20.50 million Oct-2022.pdf','Soft Gummy Candy Manufacturing Unit Rs. 100.90 million Sep-2021.pdf','Spices Processing Packing Marketing Rs. 15.09 million Nov-2023.pdf','Steel Furniture Manufacturing Unit Rs. 8.93 million May-2021.pdf','Steel Nail Making Unit Rs. 38.05 million Mar-2020.pdf','Steel Wire Drawing Unit Rs. 99.71 million Mar-2020.pdf','Sulfuric Acid Manufacturing Unit Rs. 347.32 million Jan-2023.pdf','Surgical Instrument Manufacturing Unit Rs. 19.39 million Dec-2022.pdf','Table Cutlery Manufacturing Unit Rs. 32.55 million Sep-2022.pdf','Teflon Tape Manufacturing Unit Rs. 54.38 million Feb-2021.pdf','Thermoform Food Container Glass Manufacturing Unit Rs. 109.65 million Feb-2021.pdf','Tissue Paper Converting Unit Rs. 36.22 million Mar-2020.pdf','Tissue Paper Manufacturing Unit Rs. 85.09 million Feb-2021.pdf','UPS and Stabilizer Assembling Unit Rs. 4.02 million Jun-2022.pdf','UPVC Window Profiles Production Unit Rs. 76.34 million Dec-2021.pdf','Vegetables Dehyderation Unit Rs. 11.39 million Dec-2023.pdf','Water and Fireproof Cloth Manufacturing Unit Rs. 54.01 million Feb-2021.pdf','Wheelchair Manufacturing Unit Rs. 5.65 million Dec-2021.pdf','Wood Saw Mill and Seasoning Plant Rs. 86.64 million Dec-2022.pdf','Zip Manufacturing Unit Rs. 6.88 million May-2021.pdf']

agricultural_and_farming_ventures = ['Aviculture Canary Birds Farming Rs. 2.16 million Jun-2020 (1).pdf',
'Aviculture Canary Birds Farming Rs. 2.16 million Jun-2020.pdf',
'Biofloc Fish Farming Rs. 11.54 million Dec-2023.pdf',
'Calf Fattening Farm Premium Feedlot Fattening System Rs. 38.41 million Sep-2023.pdf',
'Cold Storage Fruit Vegetable Rs. 380.47 million Sep-2023.pdf',
'Cut Flower Farm Gladiolus Marigold Statice and Chrysanthemum Rs. 11.75 million Jun-2023.pdf',
'Dairy Farm 100 Cows Rs. 186.64 million Jun-2023.pdf',
'Dairy Farm 25 Cows Rs. 51.75 million Jun-2023.pdf',
'Dairy Farm 50 Cows Rs. 90.33 million Apr-2025.pdf',
'Dairy Farm 75 Cows Rs. 141.42 million Jun-2023.pdf',
'Goat Fattening Farm 800 Animals Rs. 13.42 million Sep-2023.pdf',
'Inland Fish Farming Rs. 17.83 million Mar-2022.pdf',
'Intensive Goat and Sheep Breeding Farm Rs. 11.94 million Sep-2023.pdf',
'Layer and Breeding Farm Rs. 7.79 million Sep-2022.pdf',
'Maize Silage Unit Rs. 6.59 million May-2022.pdf',
'Mini Dairy Processing Plant Pasteurized Milk Cheese and Yogurt Rs. 82.28 million Sep-2023.pdf',
'Modified CA Cold Storage 1000 MT Rs. 324.59 million Nov-2023.pdf',
'Mushroom Farming Rs. 22.29 million Nov-2023.pdf',
'Off-Season Vegetable Farming High Tunnel Rs. 16.58 million Nov-2023.pdf',
'Organic Chicken Farming and Shop Rs. 14.16 million Apr-2021.pdf',
'Pedigree Dog Breeding Farm Rs. 10.88 million May-2021.pdf',
'Plant Nursey Rs. 5.53 million Jun-2022.pdf',
'Poultry Breeder Farm Rs. 4.84 million Jun-2020.pdf',
'Rabbit Farming Rs. 12.58 million Mar-2021.pdf',
'Rental Unit for Maize Silage Rs. 6.52 million Jan-2024.pdf',
'Rhodes Grass Hay 50 Acre Rs. 28.97 million Nov-2023.pdf',
'Shrimp Farming and Processing Rs. 27.87 million Feb-2021.pdf',
'Silo Based Storage System Rs. 131.63 million Dec-2023.pdf',
'Strawberry Cultivation Rs. 1.27 million Jun-2022.pdf']

service_based_ventures = ['Air Conditioner and Generator Rental Service Center Rs. 86.24 million Jan-2023.pdf',
'Air Conditioner and Refrigerator Installation and Service Centre Rs. 3.46 million Oct-2022.pdf',
'Auto Detailing and Paint Shop Rs. 4.88 million Feb-2021.pdf',
'Auto Repair Service Workshop Rs. 4.33 million Jun-2023.pdf',
'Automobile Diagnostic Car Detailing Rs. 1.9 million May-2020 (1).pdf',
'Automobile Diagnostic Car Detailing Rs. 1.9 million May-2020.pdf',
'Banquet Hall 500 Guests Rs.105.04 million May-2023.pdf',
'Beach Resort Rs. 74.82 million Feb-2021.pdf',
'BPO Business Processing Outsourcing Office with 100 Resources Rs. 67.82 million Nov-2023.pdf',
'Call Center with 100 Seats Rs. 50.15 million Nov-2023.pdf',
'Cell Phone Repair Center Rs. 2.26 million Dec-2023.pdf',
'Courier Service Rs. 22.47 million Jun-2021.pdf',
'Coworking Space Rs. 55.67 million Dec-2022.pdf',
'Day Care Center Rs. 6.06 million Feb-2021.pdf',
'Decoration Catering Services Rs. 9.59 million Dec-2021.pdf',
'Dermatology Clinic Rs. 10.41 million Sep-2022.pdf',
'Desert Safari - Tharparkar Adventures Rs. 27.85 million Jun-2022 .pdf',
'Diagnostic Laboratory Rs. 5.63 million Apr-2020.pdf',
'Digital Marketing Agency Rs. 5.70 million Nov-2023.pdf',
'Drama and Film Producton Equipment Rental Services Rs. 83.95 million Dec-2022.pdf',
'Education Immigration Consultants Rs. 6.50 million May-2021.pdf',
'Establishment of Travel Agencies Tour Operators Rs. 5.54 million Sep-2021 (1).pdf',
'Establishment of Travel Agencies Tour Operators Rs. 5.54 million Sep-2021.pdf',
'Event Management Complex Rs. 92.12 million Oct-2021.pdf',
'Fabrication of Aluminum Doors and Windows Rs. 4.32 million Oct-2022.pdf',
'Fabrication of Architectural and Ornamental Metal Work Rs. 4.66 million Sep-2021.pdf',
'Fitness Studio Rs. 14.51 million Jun-2024.pdf',
'Food Catering Service Rs. 5.04 million Sep-2022.pdf',
'Framing Services Rs. 4.39 million Oct-2022.pdf',
'Freight Forwarding Company Rs. 15.03 million Jun-2021.pdf',
'Gemstone Lapidary Rs. 3.45 million Jan-2021.pdf',
'Gemstones Cutting and Faceting Rs. 1.82 million Jun-2022.pdf',
'Genset Repairing Workshop Rs. 0.59 million Feb-2021.pdf',
'Gents Salon Rs. 2.13 million Dec-2022.pdf',
'Glass Ceramic Coating of Vehicles Auto Detailing Rs. 4.65 million May-2021.pdf',
'Guest House Rs. 14.19 million Apr-2021.pdf',
'Health Fitness Club Rs. 5.04 million Dec-2020.pdf',
'Heavy Construction Equipment Rental and Leasing Services Rs. 153.42 million Sep-2021.pdf',
'Heavy Truck Repair And Maintenance Workshop Rs. 18.97 million Feb-2021.pdf',
'High School Franchise Rs. 16.10 million Sep-2023.pdf',
'Home Carpet Cleaning Service Rs. 3.43 million Dec-2023.pdf',
'Homemade Lunch Box and Tiffin Service Rs. 4.14 million Mar-2024.pdf',
'Household Solar Systems Distribution Rs. 4.31 million Nov-2023.pdf',
'Indoor Amusement Park Rs. 25.57 million Dec-2022.pdf',
'Indoor Cricket And Futsal Turf Sports Complex Rs. 9.64 million Oct-2022.pdf',
'Inter-City Passenger Transport Company Rs. 122.51 million Oct-2022.pdf',
'Laundry and Dry Cleaning Rs. 5.15 million Dec-2020.pdf',
'LPG Storage and Filling Station Rs. 119.98 million Sep-2023.pdf',
'Medical Clinic Rs. 2.6 million Aug-2021.pdf',
'Mobile Banquet Hall Rs. 32.62 million Sep-2024.pdf',
'Mobile Pick and Drop-off Laundry Service Rs. 8.46 million Dec-2024.pdf',
'Modern Car Wash Station Rs. 9.84 million Mar-2024.pdf',
'Modernistic Auto-Dock Rs. 4.57 million Jun-2024.pdf',
'Motorcycle and Scooty Repair Workshop Rs. 3.53 million Jul-2022.pdf',
'On The Go Car Detailing Service Rs. 11.37 million Mar-2025.pdf',
'Online Teaching Rs. 6.76 million Sep-2023.pdf',
'Packing and Moving Service Rs. 3.73 million Nov-2020.pdf',
'Pest Control Service Rs. 6.03 million May-2021.pdf',
'Pharmaceutical Distribution and Marketing Unit Rs. 103.89 million Dec-2022.pdf',
'Physiotherapy Clinic Rs. 4.58 million Mar-2021.pdf',
'Pick and Drop Service Rs.2.30 million Nov-2020.pdf',
'Polytechnic IT Training Institiute Rs. 32.22 million Dec-2022.pdf',
'Prenatal Centre Rs. 5.08 million May-2021.pdf',
'Printing and Photocopy Shop Rs. 2.75 million Jun-2023.pdf',
'Private Library Rs. 6.13 million Sep-2023.pdf',
'Publishing House Rs. 82.71 million Oct-2022.pdf',
'Refrigerated Transportation Service Rs. 6.37 million May-2021.pdf',
'Security Agency Rs. 13.18 million Jun-2021.pdf',
'Service Station Rs. 5.37 million Dec-2021.pdf',
'Setting Up General Medical and Surgical Hospital Rs. 47.71 million Nov-2021.pdf',
'Setting Up Surveying Instrument Repair Unit Rs. 4.65 million Sep-2021.pdf',
'Setting up Tractor and Agricultural Equipment Repair Unit Rs. 3.4 million Aug-2021.pdf',
'Setting-up Automotive Glass Replacement Shop Rs. 1.75 million Aug-2021.pdf',
'Setting-up Coin Operated Laundry and Dry Cleaning Rs. 4.57 million Aug-2021.pdf',
'Setting-up Guard and Armored Car Services Unit Rs. 166.98 million Sep-2021.pdf',
'Setting-up Kidney Dialysis Center Rs. 17.88 million Aug-2021.pdf',
'Setting-up Medical Laboratories Rs. 20.88 million Sep-2021.pdf',
'Setting-up Offices and Clinics of Dentists Rs. 4.01 million Nov-2021.pdf',
'Skilled Nursing Care Facilities Rs. 3.89 million Aug-2021.pdf',
'Small Courier Delivery Services Rs. 1.88 million May-2021.pdf',
'Small Size Corporate Law Practicing Firm Rs. 5.25 million May-2021.pdf',
'Smart Home Automation Services Rs. 7.81 million Dec-2023.pdf',
'Social Media Marketing Agency Rs. 4.02 million Feb-2021.pdf',
'Solar Power Solar Heating Systems Designing and Installation Services Rs. 4.71 million May-2021.pdf',
'Student Hostel Rs. 6.74 million Mar-2021.pdf',
'Swimming Pool Rs. 125.79 million Feb-2021.pdf',
'Trading House for Industrial Machinery and Equipment-Textile and Allied Sector Rs. 35.94 million Nov-2021.pdf',
'Travel and Tour Agency Umrah Hajj Services Rs. 3.45 million Dec-2020.pdf',
'Trout Reefer Van Rs. 8.61 million May-2022.pdf',
'Trucking Company Rs. 135.48 million Jun-2022.pdf',
'Vehicle Tracking Company Rs. 9.44 million Mar-2022.pdf',
'Virtual Reality Gaming Zone Rs. 17.90 million Jan-2021.pdf',
'Watch Restoration and Service Centre Rs. 4.67 million Mar-2025.pdf']

retail_and_wholesale_ventures = ['Dairy Shop Rs. 6.06 million Sep-2023.pdf',
'Departmental Store Rs. 24.38 million Dec-2021.pdf',
'Filling Station Rs. 95.58 million Mar-2021.pdf',
'Food Corner on Wheels Rs. 7.60 million Feb-2021.pdf',
'Fruit Vegetable Mobile Shop Rs. 1.93 million Dec-2020.pdf',
'Furniture Show Room Rs. 16.38 million Sep-2023.pdf',
'Homemade Canned Food Business Rs. 10.43 million Apr-2021.pdf',
'Medical Store Rs. 5.95 million Oct-2021.pdf',
'Mineral Water Distribution Model Rs.2.80 million Jun-2022.pdf',
'Mineral Water Smart Filling Shop Rs. 1.85 million Jun-2022.pdf',
'Pet Store Rs. 35.90 million Oct-2022.pdf',
'Retail or Wholesale Outlet for Used Motor Vehicle Parts - Commercial Carriage Vehicles Rs. 14.31 million Sep-2021.pdf',
'Retail Store for Medical Dental and Hospital Equipment and Supplies Rs. 13.29 million Aug-2021.pdf',
'Retail Store for Sporting and Recreational Goods and Supplies Rs. 9.87 million Nov-2021.pdf',
'Retail Store for Timber Products Rs. 13.76 million Aug-2021.pdf',
'Solar PV Home Distribution Business Rs. 3.9 million Jan-2020.pdf',
'Sugarcane Juice Shop Rs. 2.53 million Sep-2022.pdf',
'Superstore Rs.41.33 million Jun-2024.pdf']

# 2. Agreements & Contracts
general_and_service_agreements = ['Administrative Services Agreement.pdf',
'Agreement for Call Centre Support.pdf',
'Agreement for Employees Transport Services.pdf',
'Agreement for hiring Financial Advisory Service.pdf',
'agreement for hiring services of an accountant.pdf',
'agreement for hiring the services of auditor.pdf',
'Agreement for Professional Services.pdf',
'Architectural Services Agreement.pdf',
'Carrier Services Agreement.pdf',
'catering services contract.pdf',
'Consulting Agreement Long.pdf',
'Consulting Agremeent Short.pdf',
'Data Provider Agreement.pdf',
'Data Punching Agreement.pdf',
'editorial services contract.pdf',
'Engineering Services Agreement.pdf',
'event photography contract.pdf',
'event planner management contract.pdf',
'Hiring Agency Agreement.pdf',
'hiring agency contract, agreement for recruitment of personnel.pdf',
'Independent Contractor Agreement.pdf',
'IT SUPPORT AND MAINTENANCE AGREEMENT.pdf',
'janitorial services Contract.pdf',
'Legal Consultancy Agreement.pdf',
'Legal Retainership Contract.pdf',
'legal auditing contract.pdf',
'Logistics Services Agreement.pdf',
'Maintenance Agreement.pdf',
'Managerial Services Agreement.pdf',
'Network Services Provider Agreement.pdf',
'performance contract.pdf',
'Programming Services Provider Agreement.pdf',
'Quality AssuranceControl Agreement.pdf',
'Restaurant Management Agreement.pdf',
'Security Services Contract.pdf',
'Solar Energy Equipment Maintenance Agreement Sep-2022.pdf',
'Sub Contractor Agreement.pdf',
'Technical Services Agreement.pdf',
'Training Services Agreement.pdf',
'Travel Services Agreement.pdf',
'venue hire agreement.pdf',
'Waste disposal Services Agreement.pdf',
'LCC_Agreement_for_Maintenance_Services.pdf',
'LCC_Agreement_to_hire_a_Consultant_(General).pdf']

sales_purchase_distribution_and_agency_agreements = ['agency agreement for sale of manufactured goods (1).pdf',
'agency agreement for sale of manufactured goods.pdf',
'Agreement for Authorized Dealership.pdf',
'Agreement for Export of Fresh Fruits.pdf',
'Agreement for Export of Sports Goods.pdf',
'Agreement for Export of Surgical Goods.pdf',
'Agreement for Import of Machinery.pdf',
'Agreement for Import of Technology.pdf',
'Agreement for Import of Vehicles.pdf',
'Agreement for Purchase of Product Design.pdf',
'agreement for purchase of accounting software.pdf',
'agreement for retail trading.pdf',
'Agreement for Sale of Allotment Rights.pdf',
'agreement for sale of bottled watercarbonated drinksjuices etc.pdf',
'agreement for sale purchase of computer equipment.pdf',
'agreement for sale purchase of dairy products.pdf',
'agreement for sale purchase of fruits vegetables.pdf',
'agreement for sale purchase of furniture.pdf',
'agreement for sale purchase of grains.pdf',
'agreement for sale purchase of livestock animals.pdf',
'agreement for sale purchase of office stationery and equipment.pdf',
'agreement for salepurchase of books.pdf',
'agreement for salepurchase of electric appliances.pdf',
'agreement for salepurchase of horticulture produce.pdf',
'agreement for salepurchase of kitchenware.pdf',
'agreement for salepurchase of ready made garments.pdf',
'agreement for salepurchase of software.pdf',
'agreement for salepurchase of spare parts.pdf',
'agreement for wholesale trading.pdf',
'Agreement to Rescind Agreement ot Sell.pdf',
'Commercial Contract Payment Agreement.pdf',
'Commission Agreement.pdf',
'Contract for Sale of Goods.pdf',
'Contract for transportation of Raw MaterialFinished Goods.pdf',
'DISTRIBUTION AGREEMENT- SOFTWARE AND MULTIMEDIA.pdf',
'Distribution Agreement.pdf',
'Distributorship Agreement.pdf',
'Franchise Agreement for Sale of Goods.pdf',
'franchise agreement for sale of manufactured goods.pdf',
'installment equipment sale agreement.pdf',
'International Distributorship Agreement.pdf',
'International Exclusive Agency Agreement.pdf',
'International Franchise Agreement.pdf',
'Retail Agreement.pdf',
'Shipping Agreement.pdf',
'LCC_Agreement_for_Exclusive_Supply_of_Goods_Manufactured.pdf',
'LCC_Agreement_to_Sell (1).pdf',
'LCC_Agreement_to_Sell.pdf',
'LCC_Buying_-_Selling_Agency_Agreement.pdf',
'LCC_Hire_purchase_agreements.pdf',
'LCC_Machinery_purchase_Agreement.pdf',
'LCC_Prepared_Food_Franchise_Agreement.pdf']

lease_rental_and_real_estate_agreements = ['Agreement for Extension of LEase.pdf',
'agreement for maintenance of business premises.pdf',
'Agreement for Permission to Sublet.pdf',
'Agreement for the Lease of Agricultural Land Sep-2023.pdf',
'agreement to terminate lease agreement.pdf',
'agreemnt for maintenance of electric office equipment.pdf',
'Assignment of LeaseRent Agreement.pdf',
'Construction Contract.pdf',
'Equipment LEase Agreement.pdf',
'Manufacturing facility lease agreement.pdf',
'Sub Lease Agreement.pdf',
'Warehouse LEase Agreement.pdf',
'LCC_Agreement_to_Construct_a_building_on_Plot.pdf',
'LCC_Lease_Deed_to_acquire_land_for_CNG_station.pdf',
'LCC_Rent_Deed.pdf']

employment_and_hr_related_agreements = ['employee invention agreement.pdf',
'Employment Agreement Part Time.pdf',
'Employment Agreement Permanent.pdf',
'Employment Agreement Temporary.pdf',
'Model Employment Contract.pdf']

financial_and_banking_agreements = ['agreement to finance- traditional banking.pdf',
'agreement to finance-Islamic banking.pdf']

intellectual_property_and_licensing_agreements = ['coownership agreeemnt for intellectual property.pdf',
'Copyright Assignment Agreement.pdf',
'copyrights license agreement.pdf',
'DOMAIN NAME ASSIGNMENT AGREEMENT.pdf',
'Intellectual Property Assignment Agreement.pdf',
'intellectual property license agreement (1).pdf',
'Intellectual Property License Agreement.pdf',
'Intellectual Property Purchase Agreement.pdf',
'Intellectual Property Sale Agreement.pdf',
'License Agreement.pdf',
'License for Overseas Manufacturing and Sales.pdf',
'Manufacturing license agreement.pdf',
'patents assignment agreement.pdf',
'SOFTWARE LICENSE AGREEMENT.pdf',
'Trademark Assignment Agreement.pdf',
'Trial Software License Agreement formating problem.pdf',
'LCC_Trademark_license_agreement.pdf']

manufacturing_supply_and_packaging_agreements = ['Agreement for Packaging of Finished Goods.pdf',
'Agreement for Supply of Raw Material.pdf',
'Agreement for the Storage of Agricultural Produce Sep-2023.pdf',
'Exclusive Manufacturing Agreement.pdf',
'Inventory Management Agreement.pdf',
'Manufacturing Agreement.pdf',
'Manufacturing Sublicense Agreement.pdf',
'Packaging Agreement.pdf',
'Standard Manufacturing Agreement.pdf',
'LCC_Manufacturing_&_Supply_of_Furniture_Agreement.pdf']

marketing_advertising_and_promotion_agreements = ['advertisement agreement (print media).pdf',
'advertisement agreement (radio).pdf',
'advertisement agreement (television channels).pdf',
'advertisement agreement (through cable operators).pdf',
'advertising agency agreement.pdf',
'agreement for designing of promotional material.pdf',
'agreement for printing of promotional material.pdf',
'agreement for publishing of booksbooklets.pdf',
'avertisement agreement (internet).pdf',
'Co-Branding Agreement for Marketing May-2021.pdf',
'content provider agreeemnt.pdf',
'event sponsorship agreement.pdf',
'Joint Marketing Agreement.pdf',
'Printing and Publishing Agreement.pdf',
'Product Designing Agreement.pdf',
'Promotion and Product Placement Agreement.pdf',
'Sponsorship Agreement.pdf',
'LCC_Agreement_to_Appoint_Sole_Advertising_Agent.pdf',
'LCC_Agreement_to_Use_Wall_for_advertising.pdf',
'LCC_Exhibition_of_advertisements_in_a_cinema.pdf',
'LCC_Terms_Conditions_For_The_Display_Banner_Advertisements.pdf']

partnership_joint_venture_and_business_structure_agreements = ['Joint Venture Agreement.pdf',
'JVA with specified Geographical Boundaries.pdf',
'Non Exclusive JVA.pdf',
'LCC_Agreement_between_Partners_to_Convert_the_Partnership_Business_into_a_Private_Limited_Company.pdf',
'LCC_Deed_of_Dissolution_of_Partnership.pdf',
'LCC_Partnership_Deed.pdf']

confidentiality_and_non_disclosure_agreements = ['Client confidentiality Agreement.pdf',
'Confidentiality Agreement.pdf',
'Confidentiality and Non-Disclosure Agreement NDA Apr-2022.pdf',
'Conflict of Interest Agreement.pdf',
'Contractor-Consultant Confidentiality Agreement.pdf',
'Mutual non disclosure Agreement.pdf',
'Non compete Agreement.pdf',
'Non Competition Agreement.pdf',
'Non Disclosure Agreement (1).pdf',
'Non disclosure Agreement.pdf',
'WEBSITE DESIGN NONDISCLOSURE AGREEMENT.pdf',
'WEBSITE DESIGN NONDISCLOSURE AGREEMENT.pdf',
'exclusivity agreement.pdf']

website_and_online_service_agreements = ['Agreement For Shared Web Hosting.pdf',
'AGREEMENT FOR WEBSITE HOSTING.pdf',
'AGREEMENT TO PURCHASE DOMAIN NAME.pdf',
'ONLINE SUBSCRIPTION AGREEMENT.pdf',
'Web Sales Agreement.pdf',
'WEBSITE CONTRIBUTING WRITER AGREEMENT.pdf',
'Website Design Agreement.pdf',
'Website Promotion Agreement.pdf',
'WEBSITE SERVICE AGREEMENTTERMS OF USE.pdf']

indemnification_gurantee_and_liability_agreements = ['Contractor Indemnification Agreement.pdf',
'corporate guarantee.pdf',
'Indemnification Agreement.pdf',
'Personal Guarantee.pdf',
'personal injury liability release agreement.pdf',
'waiver of liability.pdf',
"participant's assumption of risks.pdf"]

miscellaneous_agreements_and_deeds = ['Agreement for broadcasting and use of production facilities.pdf',
'LCC_Deed_of_Mortgage.pdf',
'LCC_Deed_of_Revocation_of_Power_Of_Attorney (1).pdf',
'LCC_Deed_of_Revocation_of_Power_Of_Attorney.pdf',
'LCC_Mortgage_Deed_(For_Bank_Loans).pdf',
'Sale Deed.pdf',
'Waranty Agreement.pdf',
'Product Warranty.pdf']

# 3. Notices, Letters, & Formal Transactions
order_and_transaction_related_notices = ['acceptance and acknowledgment.pdf',
'cancellation of po.pdf',
'conditional acceptance of goods.pdf',
'confirmation of verbal order.pdf',
'damaged goods acceptance notice.pdf',
'defective goods notice.pdf',
'demand for delivery.pdf',
'demand for explanation of goods rejected.pdf',
'demand for payment.pdf',
'demand to acknowledge delivery.pdf',
'notice for return of goods.pdf',
'notice of acceptance of order.pdf',
'notice of cancellation of delayed order.pdf',
'notice of delayed shipment.pdf',
'notice of delivery witheld at place.pdf',
'notice of receipt on incomplete shipment.pdf',
'notice to stop goods in transit.pdf',
'rejection of non conforming goods.pdf',
'rejection of order.pdf',
'request for replacement of damaged merchandise.pdf',
'return of goods sold.pdf']

legal_and_contractural_notices = ['contract terms violation notice.pdf'
'eviction notice.pdf'
'notice alleging passing off.pdf'
'notice of infringement of ip.pdf'
'notice to tenant for rent default.pdf'
'Notice of Termination.pdf']

employment_related_notices_and_letters = ['employee dismissal notice.pdf',
'Employee Personal File.pdf',
'employee restoration notice.pdf',
'employee show cause.pdf',
'employee suspension notice.pdf',
'employee warning notice.pdf',
'Employment Confirmation Letter.pdf',
'LCC_Letter_of_Appointment_as_a_Permanent_Workman.pdf',
'LCC_Letter_of_Appointment_as_a_Probationer.pdf',
'LCC_Letter_of_Appointment_as_a_Temporary_Workman.pdf',
'LCC_Notice_of_Termination_of_Workman.pdf',
'LCC_Order_of_Termination_of_Workman.pdf',
'Offer Letter.pdf']

corporate_and_shareholder_notices_resolutions = ['directors resolution to call agm.pdf',
'directors resolution to call eogm.pdf',
'letter to shareholders with resolution to be adopted.pdf',
'minutes for agm.pdf',
'minutes for eogm.pdf',
'minutes of bod meeting.pdf',
'notice of agm.pdf',
'notice of dissolution of partnership.pdf',
'notice of eogm.pdf',
'request for replacement of share certificate.pdf']

financial_and_banking_letters_notices = ['authority to debit markup.pdf',
'finance request letter.pdf',
'Letter of Credit Sep-2023 (1).pdf',
'Letter of Credit Sep-2023.pdf',
'Letter of Hypothecation for Current Assets.pdf',
'Letter of Hypothecation for Fixad Assets.pdf',
'Letter of Pledge.pdf',
'letter of continuity.pdf']

# 4. Guides, Procedures & Hot-To Documents
business_setup_and_registration = ['Association not for profit under section 42 of companies act 2017.pdf',
'Computer Software Copyright Registration Procedure May - 2018.pdf',
'Copyrights Registration Procedure Jun-2021.pdf',
'Dissolution of Defunct Limited Liability Company.pdf',
'E-Enrolment For an Individual to use the FBR Portal Mar-2022.pdf',
'How to become a member of Chambers of Commerce Industry Sep-2021.pdf',
'How to Register Business with Balochistan Revenue Authority BRA Dec-2022.pdf',
'Industrial Design Registration Apr-2022.pdf',
'Legal Requirements for Starting a SME Business in Pakistan.pdf',
'Patent Registration Procedure 2018.pdf',
'Procedure for Acquiring Industrial Plot in Punjab Feb-2021.pdf',
'Procedure for Obtaining License of Medical Store in Punjab.pdf',
'Procedure for Obtaining NOC for Conversion of Residential area into Commercial.pdf',
'Procedure to Obtain a Telephone Connection Sep-2020.pdf',
'Procedure to Obtain Electricity Connection Sep-2020.pdf',
'Procedure to Obtain Gas Connection from SNGPL Jun-2022.pdf',
'Registration - Licensing And Other Legal Requirements For Recruiting Agencies Overseas Employment Overseas Employment Promotors Dec-2021.pdf',
'Registration - Licensing And Other Requirements For Money Exchange Company Apr-2025.pdf',
'Registration and Incorporation Procedure for a Limited Liability Partnership 2021.pdf',
'Registration and Licensing with Punjab Food Authority.pdf',
'Registration for a Single Member Company SMC for a Foreign National 2020.pdf',
'Registration Procedure for Partnership March-2021.pdf',
'Trade Mark Registration Proceudre Dec-2022.pdf',
'Web Based One Customs WeBOC Sep-2020.pdf',
'C-5 Opening Online Web Based One Customs WEBOC Account.pdf']

business_planning_and_startup = ['Choosing a Business for Yourself.pdf',
'Common Startup Mistakes.pdf',
'D-1 Prepare Yourself for Business.pdf',
'D-2 Startup Costing of Business.pdf',
'D-3 Starting a New Business.pdf',
'D-4 Buying an Existing Business.pdf',
'D-5 Business Startup for Overseas.pdf',
'D-6 Starting Online Business.pdf',
'How to Come Up With Good Business Idea Dec-2023.pdf',
'How to Make a Business Plan.pdf',
'How to start Home-Based Business Dec-2024.pdf',
'How To Successfully Pitch Your Business Idea To Investors Mar-2023.pdf',
'LCC_Contract_Negotiation_Writing_and_Management_Guidelines-Tips.pdf']

operational_and_quality_management = ['Compliance With Environmental Laws In Pakistan Nov-2021.pdf',
'Disciplinary Rules and Procedures.pdf',
'Food Safety Compliance Requirements.pdf',
'Grievance Handling Procedure.pdf',
'Guide of Pakistan Standards Quality Control Licensing Requirement Feb-2022.pdf',
'Hazard Analysis Critical Control Point System.pdf',
'How To Have ISO Certification For Your Business Mar-2023.pdf',
'Hygiene Management in Restaurants Cafes.pdf',
'Organic Pest Management for Commercial Farming.pdf',
'Pest Management in Food Processing.pdf',
'Quality Management - Guidelines for Food Sector SMEs.pdf']

financial_management_and_funding = ['Assessing Working Capital Requirement.pdf',
'Financing Your Business.pdf',
'How to Approach Banks.pdf',
'Managing Business Cash Flows.pdf',
'Managing Inventory Costs.pdf',
'Managing Invoicing and Payments.pdf',
'Understanding Business Assets and Liabilities.pdf']

agricultural_practices_and_guidelines = ['Backgrounding of Calves for Beef Fattening 2021.pdf',
'FAQs - Commercial Dairy Farming on Environmentally Controlled Housing ECH System.pdf',
'FAQs - Goat Fattening Farm Jan-2024.pdf',
'FAQs on Effective Mastitis Control at Dairy Farm - Urdu Jun-2022.pdf',
'FAQs on Effective Mastitis Control at Dairy Farm.pdf',
'FAQs on Good Practices for Milking Hygiene at Dairy Farms - Urdu Jun-2022.pdf',
'FAQs on Good Practices for Milking Hygiene at Dairy Farms.pdf',
'FAQs on Importance of Bio Gas Technology on Dairy and Livestock Farms 2024.pdf',
'FAQs on Profitable Commercial Dairy Farming on ECH System - Urdu Mar-2022 .pdf',
'Feeding and Nutrition Management for Dairy Cattle - Urdu Apr-2022.pdf',
'Feeding and Nutrition Management for Dairy Cattle.pdf',
'Guidelines - Selection of Sacrificial Animals Eid ul Azha May-2024.pdf',
'Hot Water Treatment for Mango Export 2022.pdf',
'How to Minimize Heat Stress in High Yielding Cows.pdf',
'Hydroponic Farming System.pdf',
'Importance of Heifer Development for Dairy Farming.pdf',
'Modern Techniques of Farming Goat and Sheep Sep-2023.pdf',
'Selection and Culling of Commercial Dairy Heifers.pdf',
'Selection of Beef Calves for Fattening.pdf',
'Tunnel Farming.pdf',
'Understanding Beef Grading and Carcuss Cuts 2024.pdf']

marketinig_and_sales_guides = ['E-1 Unique Selling Proposition.pdf',
'E-10 Social Media.pdf',
'E-11 Advertising.pdf',
'E-12 Positioning Your Business.pdf',
'E-13 Marketing Plan.pdf',
'E-14 Marketing to Young Generation.pdf',
'E-15 Customer Relationship Management.pdf',
'E-16 Converting Trade Leads into Successful Sales.pdf',
'E-17 Distribution Channels of Your Business.pdf',
'E-18 Search Engine Optimization.pdf',
'E-2 Benchmarking your Business.pdf',
'E-3 Pricing Strategies.pdf',
'E-4 Developing a Marketing Strategy.pdf',
'E-5 Selling Products and Services.pdf',
'E-6 Product Labelling.pdf',
'E-7 Buying and Selling Online.pdf',
'E-8 Customers Services Management.pdf',
'E-9 Market Research.pdf',
'Marketing a Small Business Sep-2024.pdf',
'Managing your Business Sales.pdf',
'Promotion and Advertising.pdf',
'TERMS AND CONDITIONS OF SALE OF GOODS ONLINE.pdf',
'TERMS OF BUSINESS FOR ADVERTISING ONLINE.pdf']

general_business_operations_guides = ['B-1 Crisis Management.pdf',
'B-2 Cyber Security.pdf',
'B-3 Business Supply Management.pdf',
'B-4 Managing and Developing Human Resource.pdf',
'B-5 Risk Assessment and Planning.pdf',
'B-6 Growing Your Business.pdf',
'B-7 Succession Plan.pdf',
'B-8 Managing Logistics and Warehousing.pdf',
'B-9 Managing Supply Chain.pdf',
'C-1 Importing Goods.pdf',
'C-2 Exporting Goods.pdf',
'C-4 Business Structures and Types.pdf',
'Export Documentation-Documents Required to Export Goods from Pakistan Dec-2024.pdf',
'Inventory Management for SMEs.pdf',
'Outsourcing in Business Mechanisms and Illustrative Examples Jun-2024.pdf']

# 5. Sector Reports, Market Analysis & Industry Overviews
general_economy_and_sme_sector = ['Climate Change Vulnerability Index of SMEs in Pakistan 2024.pdf',
'COVID-19 SME Liquidity Support and Business Formalization Survey Report 11-05-2020.pdf',
'Estimating Manufacturing SMEs Contribution to Pakistans GDP Jun-2022.pdf',
'ILO_Pakistan_SMEDA mapping informality enterprises.pdf',
'Preliminary Assessment of Impact of Floods on SMEs Dec-2022.pdf',
'Sector Briefs- Highlighting Investment Opportunities 2025.pdf',
'Situational Analysis of SMEs during COVID-19 - Full Survey Report Feb 2021.pdf',
'SMEDA ADB WE Diagnostic Summary.pdf',
'SMEDA - ADBI Report on Impact of COVID-19 on SMEs.pdf',
'smeda_2025_05_04T04_00_13_122Z.pdf',
'smeda_2025_05_04T04_01_13_232Z.pdf',
'SMEs BDS Need Assesment - Survey Report 2021.pdf',
'Study of Existing Income Tax Regime for SMEs - Summary 2023.pdf',
'Women Entrepreneurship in Balochistan 2019.pdf']

agriculture_and_food_sector_reports = ['Agriculture Mechanization.pdf',
'Balochistan Food Authority 2022.pdf',
'Balochistan Fruits 2024.pdf',
'Cheese- Value added dairy product-prospects for Pakistan 2023.pdf',
'Dairy and Livestock Sector of Pakistan 2024.pdf',
'Dates Sector Balochistan 2020.pdf',
'Dehydration of Fruits 2022.pdf',
'Food Canning Preservation Opportunities for Small Business.pdf',
'Food Certifications - Pakistan.pdf',
'Food Preservation.pdf',
'Fried Onion Market Sector and Potentials in Pakistan Mar-2022.pdf',
'High Value Food Products for SMEs 2024.pdf',
'Honey Farming - Small Busniess.pdf',
'Honey Processing Rs. 3.03 million Nov-2020.pdf',
'Investment Potential of Maize Value Added By-Products in South Punjab Jun-2024.pdf',
'Livestock Report 2019.pdf',
'Oil Seed Crops.pdf',
'Olive Commercial Cultivation Dec-2022.pdf',
'Olive Sector 2023.pdf',
'Poultry Sector Profile of Balochistan 2025.pdf',
'Rice Sector 2021.pdf',
'Sericulture - Silk Production for Small Business.pdf',
'Small Scale Mushroom Farming 2024.pdf',
'Value Addition in Olive Dec-2022.pdf',
'World Red Meat Markets and Compliance Requirements 2023.pdf']

manufacturing_and_industrial_sector_reports = ['Buying Existing Franchise Dec-2022.pdf',
'Carbon Exchange and Carbon Credits 2025.pdf',
'Cold Storage Fruits Vegetables.pdf',
'Cutlery Sector - Kitchenware Cutlery 2020.pdf',
'Cutlery Sector - Non-Kitchenware Cutlery 2020.pdf',
'Cutlery Sector of Pakistan 2018.pdf',
'Electric Vehicle Market Sector and Potentials in Pakistan Dec-2021 (1).pdf',
'Electric Vehicle Market Sector and Potentials in Pakistan Dec-2021.pdf',
'Fan Sector 2018.pdf',
'Leather Apparel.pdf',
'Leather Footwear.pdf',
'Leather Goods.pdf',
'Mining Sector of Balochistan Mar-2025.pdf',
'Pharmaceutical Sector 2022.pdf',
'Raw Hides Skins and Leather.pdf',
'Renewable Energy Establishing Wind Energy Unit Sep-2021.pdf',
'SI_Apparel.pdf',
'SI_Bed-wear_and_Bed_Linen.pdf',
'SI_Bicycles.pdf',
'SI_Blankets.pdf',
'SI_Canvas_&_Canvas_Products.pdf',
'SI_Ceramics.pdf',
'SI_Cotton_&_Ginning.pdf',
'SI_Curtains_&_Furnishing.pdf',
'SI_Fisheries_Sector_of_Pakistan.pdf',
'SI_Garments_and_Made-up.pdf',
'SI_Gems_&_Jewelry.pdf',
'SI_Leather_Industry.pdf',
'SI_Spinning.pdf',
'SI_Table_Linen.pdf',
'SI_Textile_Weaving.pdf',
'SI_Towels_&_Terry_Products.pdf',
'SI_Wooden_Furniture.pdf',
'Sports Goods 2021.pdf',
'Steel Sector 2020 (1).pdf',
'Steel Sector 2020.pdf',
'Surgical Instruments 2022.pdf',
'Textile Made Up 2023.pdf',
'Trends_in_Electricity_Generation_2006-07_to_2020-21.pdf',
'Electric Vehicle Charging Station Sep-2022.pdf']

retail_and_service_sector_reports_overviews = ['auto repair shops.pdf',
'Book shops.pdf',
'Cosmetic Shops.pdf',
'courier services.pdf',
'departmental store.pdf',
'dyeing shops.pdf',
'Electronic Appliances Shops.pdf',
'Electronic Items Repair Shops.pdf',
'Garments Shops.pdf',
'Medical Stores.pdf',
'Mobile Shops.pdf',
'Photocopiers.pdf',
'Photographers,Stdios,Developers.pdf',
'Transport service providers.pdf',
'Travel Agencies.pdf',
'Wholesale Business.pdf']

# 6. Financial, Banking, & Corporate Legal Documents (Non-Agreement)
financial_banking_and_corporate_legal_documents_non_agreement = ['LCC_Account_Opening_Application_to_the_Bank.pdf',
'LCC_Account_Opening_Form_of_a_Company.pdf',
'LCC_Account_opening_form_of_a_firm.pdf',
'LCC_Authority_to_operate_the_account.pdf',
'LCC_Banking_(_Account_Opening,_Authority_to_Operate,Declaration).pdf',
'LCC_Declaration_in_favor_of_the_Bank_by_partners_of_a_firm.pdf',
'LCC_Declaration_in_favor_of_the_Bank_by_the_sole_owner_of_a_business.pdf',
'LCC_Demand_Promissory_Note.pdf',
'LCC_General_Power_of_Attorney.pdf',
'LCC_Irrevocable_General_Power_Of_Attorney_(For_Bank_Loans).pdf',
'LCC_Special_Power_of_Attorney.pdf',
'limited and general proxy.pdf',
'nominee shareholders declaration.pdf',
'promissory note.pdf',
'sample memorandum of association.pdf',
'share sale purchase agreement.pdf',
'share subscription application.pdf',
'undertaking for appropriate utilization of funds.pdf',
'website privacy policy.pdf']

# 7. Insurance Documents
insurance_documents = ['Agricultural Insurance.pdf',
'Guarantee insurance.pdf',
'Insurance Assignment.pdf',
'Insurance of Constructed Building.pdf',
'Insurance of Hypothecated Goods.pdf',
'Insurance of Immoveable Assets.pdf']

# 8. Transactional & Order Forms/Slips
transactional_and_order_forms_slips = ['bill of lading.pdf',
'packing slip.pdf',
'price quotation.pdf',
'purchase order.pdf',
'receipt for goods or services.pdf',
'sales invoice.pdf',
'sales receipt.pdf']


# for i in confidentiality_and_non_disclosure_agreements:
#   print(i)
#   print("hehe")



TOPICS = {
    'Business Feasibility Studies & Project Reports (Sector-Specific)': ['manufacturing_vantures', 'agricultural_and_farming_ventures', 'retail_and_wholesale_ventures'],
    'Agreements & Contracts': ['general_and_service_agreements', 'sales_purchase_distribution_and_agency_agreements', 'lease_rental_and_real_estate_agreements',
                               'employment_and_hr_related_agreements', 'financial_and_banking_agreements', 'intellectual_property_and_licensing_agreements',
                               'manufacturing_supply_and_packaging_agreements', 'marketing_advertising_and_promotion_agreements',
                               'partnership_joint_venture_and_business_structure_agreements', 'confidentiality_and_non_disclosure_agreements',
                               'website_and_online_service_agreements', 'indemnification_gurantee_and_liability_agreements', 'miscellaneous_agreements_and_deeds'],
    'Notices, Letters, & Formal Transactions': ['order_and_transaction_related_notices', 'legal_and_contractural_notices', 'employment_related_notices_and_letters',
                                                'corporate_and_shareholder_notices_resolutions', 'financial_and_banking_letters_notices'],
    'Guides, Procedures & Hot-to Documents': ['business_setup_and_registration', 'business_planning_and_startup', 'operational_and_quality_management',
                                              'financial_management_and_funding', 'agricultural_practices_and_guidelines', 'marketinig_and_sales_guides',
                                              'general_business_operations_guides'],
    'Sector Reports, Market Analysis & Industry Overviews': ['general_economy_and_sme_sector', 'agriculture_and_food_sector_reports', 'manufacturing_and_industrial_sector_reports',
                                                             'retail_and_service_sector_reports_overviews'],
    'Financial, Banking, & Corporate Legal Documents (Non-Agreement)': ['financial_banking_and_corporate_legal_documents_non_agreement'],
    'Insurance Documents': ['insurance_documents'],
    'Transactional & Order Forms/Slips': ['transactional_and_order_forms_slips']
  }

# classification_descriptions_updated = {
#     "manufacturing_ventures": "Pre-feasibility studies, project reports, or business plans for establishing specific manufacturing units, typically including cost estimations and production details.",
#     "agricultural_and_farming_ventures": "Documents outlining business plans, feasibility studies, or project reports for agricultural, livestock, aquaculture, and related farming enterprises.",
#     "retail_and_wholesale_ventures": "Business plans or feasibility studies for setting up retail shops, wholesale outlets, distribution models, or mobile vending businesses.",
#     "general_and_service_agreements": "Templates and examples of contracts for a wide range of professional, administrative, technical, and general business services.",
#     "sales_purchase_distribution_and_agency_agreements": "Legal documents governing the sale, purchase, import/export, distribution, and agency relationships for goods and products.",
#     "lease_rental_and_real_estate_agreements": "Contracts related to the leasing or renting of property, equipment, and agreements for construction or maintenance of premises.",
#     "employment_and_hr_related_agreements": "Templates for employment contracts (permanent, temporary, part-time) and other HR-related agreements like invention agreements.",
#     "financial_and_banking_agreements": "Agreements specifically related to financing arrangements with traditional and Islamic banking institutions.",
#     "intellectual_property_and_licensing_agreements": "Legal documents for assigning, licensing, purchasing, or selling intellectual property rights such as copyrights, patents, trademarks, and domain names.",
#     "manufacturing_supply_and_packaging_agreements": "Contracts governing manufacturing processes, supply of raw materials, packaging of goods, and inventory management.",
#     "marketing_advertising_and_promotion_agreements": "Agreements related to marketing campaigns, advertising services (print, radio, TV, internet), promotional material design, and sponsorships.",
#     "partnership_joint_venture_and_business_structure_agreements": "Legal documents for forming partnerships, joint ventures, or converting business structures.",
#     "confidentiality_and_non_disclosure_agreements": "Agreements designed to protect sensitive information shared between parties, including non-compete and exclusivity clauses.",
#     "website_and_online_service_agreements": "Contracts related to web hosting, domain name purchase, website design, online subscriptions, and terms of service for online platforms.",
#     "indemnification_gurantee_and_liability_agreements": "Legal documents where one party agrees to cover losses or damages for another, personal/corporate guarantees, and liability waivers.",
#     "miscellaneous_agreements_and_deeds": "A collection of other specific agreements and legal deeds such as mortgage deeds, powers of attorney, and sale deeds not fitting into more specific contract categories.",
#     "order_and_transaction_related_notices": "Formal communications concerning business orders, goods acceptance or rejection, delivery issues, and payment demands.",
#     "legal_and_contractural_notices": "Official notifications regarding contract violations, lease issues, intellectual property infringement, or termination of agreements.",
#     "employment_related_notices_and_letters": "Formal communications related to employment, such as appointment letters, warnings, dismissals, and termination notices.",
#     "corporate_and_shareholder_notices_resolutions": "Official documents for corporate governance, including notices for shareholder meetings (AGM/EOGM), meeting minutes, and director resolutions.",
#     "financial_and_banking_letters_notices": "Formal letters and notices used in banking and financial transactions, like letters of credit, hypothecation, and fund utilization.",
#     "business_setup_and_registration": "Guides on the legal and procedural steps for registering different types of businesses, obtaining licenses, and complying with regulatory bodies in Pakistan.",
#     "business_planning_and_startup": "Documents offering advice and frameworks for starting a new business, developing business plans, costing, and idea generation.",
#     "operational_and_quality_management": "Guides on maintaining quality standards, environmental compliance, safety procedures (like HACCP), and obtaining certifications (like ISO).",
#     "financial_management_and_funding": "Informational guides on managing business finances, working capital, invoicing, payments, and approaching banks for funding.",
#     "agricultural_practices_and_guidelines": "Practical guides, FAQs, and best practice documents for various aspects of farming, livestock management, and agricultural techniques.",
#     "marketinig_and_sales_guides": "Documents providing strategies and tips for marketing, sales, customer relationship management, branding, and online promotion.",
#     "general_business_operations_guides": "Guides covering broader aspects of running a business, such as crisis management, HR development, supply chain, logistics, and import/export processes.",
#     "general_economy_and_sme_sector": "Reports and surveys focusing on the broader SME (Small and Medium Enterprises) sector, economic impacts (like COVID-19), and policy-related studies.",
#     "agriculture_and_food_sector_reports": "Analytical reports, profiles, and market potential studies related to various agricultural products, food processing, and livestock in Pakistan.",
#     "manufacturing_and_industrial_sector_reports": "Overviews, analyses, and investment opportunity reports for various manufacturing industries, including textiles, automotive, steel, and energy.",
#     "retail_and_service_sector_reports_overviews": "Brief overviews or reports on various retail and service-based business types.",
#     "financial_banking_and_corporate_legal_documents_non_agreement": "Forms, templates, and declarations related to banking, corporate finance, and company legal formalities that are not full agreements.",
#     "insurance_documents": "Documents related to various types of business insurance, including agricultural, guarantee, and asset insurance.",
#     "transactional_and_order_forms_slips": "Standardized forms used in day-to-day business transactions, such as invoices, purchase orders, packing slips, and receipts."
# }

classification_descriptions_updated = {
  'manufacturing_ventures': 'These PDF files are business proposals, feasibility studies, or project reports for various manufacturing ventures, each detailing a specific unit or product, such as "3D Cinema" or "Bio-Degradable Plastic Bags Manufacturing Unit," alongside an investment cost in Pakistani Rupees, like "Rs. 5.81 million," and a creation or finalization date, such as "Jun-2021." The topics span diverse industries, including food and beverage (e.g., fruit juice, spices, biscuits), textiles and apparel (e.g., bed linen, hosiery), plastics and packaging (e.g., HDPE pipes, PET preforms), construction materials (e.g., ceramic tiles, marble processing), healthcare and cosmetics (e.g., oncology centers, surgical masks), electronics and electrical (e.g., LED bulbs, electric motors), chemicals and minerals (e.g., detergent powder, calcium carbonate), and specialized manufacturing (e.g., wheelchairs, zippers, candles). Each document likely includes project costs, production processes, market analysis, and financial projections to guide the establishment or expansion of these manufacturing businesses.',
  'agricultural_and_farming_ventures': 'These PDF files are business proposals or feasibility studies for agricultural and farming ventures, each detailing a specific operation, like "Dairy Farm 50 Cows" or "Biofloc Fish Farming," with investment costs in Pakistani Rupees, such as "Rs. 90.33 million," and a date, like "Apr-2025." The topics span dairy farming, poultry, aquaculture, livestock breeding, crop cultivation, floriculture, and specialty farming like mushrooms and dog breeding. They also include processing and storage solutions and support systems like plant nurseries. Each document likely covers project costs, processes, market potential, and financial projections to guide the setup or growth of these agricultural businesses.',
  'service_based_ventures': 'These PDF files are business proposals or feasibility studies for service-based ventures, detailing operations like "Modern Car Wash Station" or "Call Center with 100 Seats," with costs in Pakistani Rupees, such as "Rs. 9.84 million," and dates like "Mar-2024." Topics span automotive services, hospitality, healthcare, education, transportation, personal care, technology, and niche services like gemstone cutting. Each likely includes costs, plans, market potential, and financial projections for starting or growing these service businesses.',
  'retail_and_wholesale_ventures': 'These PDF files are business proposals for retail and wholesale ventures, outlining operations like "Dairy Shop" or "Superstore," with costs in Pakistani Rupees, like "Rs. 41.33 million," and dates like "Jun-2024." Topics include food retail, general and specialty retail, mobile retail, and wholesale distribution. Each likely details costs, plans, market potential, and financial projections for starting or growing these businesses.',
  'general_and_service_agreements': 'These PDF files are templates or contracts for general and service agreements, detailing arrangements like "Administrative Services Agreement" or "Solar Energy Equipment Maintenance Agreement," some with dates like "Sep-2022." Topics include administrative, IT, consulting, logistics, maintenance, security, event management, recruitment, and specialized services like catering and auditing. Each likely outlines service scope, responsibilities, and terms for formalizing professional or service engagements.',
  'sales_purchase_distribution_and_agency_agreements': 'These PDF files are templates or contracts for sales, purchase, distribution, and agency agreements, detailing transactions or partnerships like "Distribution Agreement" or "Agreement for Export of Fresh Fruits." Topics include sales/purchases of goods (e.g., dairy, software), import/export, distribution, franchising, and agency agreements. Each likely outlines terms and responsibilities for trade or agency relationships across industries.',
  'lease_rental_and_real_estate_agreements': 'These PDF files are templates or contracts for lease, rental, and real estate agreements, detailing terms for property or equipment use, like "Warehouse Lease Agreement" or "Agreement for the Lease of Agricultural Land Sep-2023." Topics cover leasing land or facilities, subletting, lease terminations, equipment leasing, maintenance, and construction. Each likely outlines terms and responsibilities for leasing or real estate transactions.',
  'employment_and_hr_related_agreements': 'The files include employment agreements (part-time, permanent, temporary), an employee invention agreement, and a model employment contract.',
  'financial_and_banking_agreements': 'The files cover traditional banking and Islamic banking financing agreements.',
  'intellectual_property_and_licensing_agreements': 'The files cover intellectual property co-ownership, copyright assignments and licenses, domain name transfers, IP sales and purchases, patent and trademark assignments, software licensing (including trial versions), manufacturing licenses, and trademark licensing agreements.',
  'manufacturing_supply_and_packaging_agreements': 'The files cover packaging agreements, raw material supply contracts, agricultural storage agreements, exclusive manufacturing deals, inventory management, general and sublicensed manufacturing contracts, and furniture production/supply agreements.',
  'marketing_advertising_and_promotion_agreements': 'The files cover print, radio, TV, cable, and internet advertising agreements, advertising agency contracts, promotional material design/printing, book publishing, co-branding deals, content provider agreements, event sponsorships, joint marketing, product placement, sole advertising agent appointments, wall/cinema ad space usage, and banner ad display terms.',
  'partnership_joint_venture_and_business_structure_agreements': 'The files cover joint venture agreements (general, geographically-bound, and non-exclusive), partnership deeds, conversion of partnerships into private limited companies, and partnership dissolution documents.',
  'confidentiality_and_non_disclosure_agreements': 'The files cover client confidentiality agreements, NDAs (mutual, contractor/consultant, website design), non-compete clauses, conflict of interest policies, and exclusivity arrangements.',
  'website_and_online_service_agreements': 'The files cover shared web hosting agreements, domain name purchases, online subscriptions, web sales contracts, website contributing writer agreements, website design and promotion deals, and general website service terms of use.',
  'indemnification_gurantee_and_liability_agreements': 'The files cover contractor indemnification, corporate and personal guarantees, liability waivers, injury releases, and risk assumption agreements.',
  'miscellaneous_agreements_and_deeds': 'The files cover broadcasting/production facility agreements, mortgage deeds (including bank loans), revocation of power of attorney documents, sale deeds, and product warranty agreements.',
  'order_and_transaction_related_notices': 'The files cover order acknowledgments, cancellations, delivery demands, goods acceptance/rejection notices, shipment delays, payment demands, damaged/defective goods handling, and return/replacement requests.',
  'legal_and_contractural_notices': 'The files cover contract violation notices, eviction warnings, intellectual property infringement claims, passing-off allegations, tenant rent default warnings, and termination notices.',
  'employment_related_notices_and_letters': 'The files cover employee disciplinary actions (dismissal, suspension, warnings), appointment letters (permanent, probationary, temporary), termination notices, employment confirmations, and offer letters.',
  'corporate_and_shareholder_notices_resolutions': 'The files cover AGM/EOGM notices and minutes, board meeting records, shareholder resolutions, partnership dissolution notices, and share certificate replacement requests.',
  'financial_and_banking_letters_notices': 'The files cover banking authorization letters, financing requests, letters of credit, hypothecation agreements (for current and fixed assets), pledge letters, and continuity letters.',
  'business_setup_and_registration': 'The files cover business registration procedures (non-profit associations, LLPs, partnerships, single-member companies), intellectual property registrations (copyrights, patents, trademarks, industrial designs), utility connections (electricity, gas, telephone), industrial plot acquisition, licensing (medical stores, food authority, recruiting agencies, money exchange), and customs account setup (WebOC).',
  'business_planning_and_startup': 'The files cover business planning guides (startup costing, new/existing/online/home-based businesses), idea generation, investor pitching, common startup mistakes, overseas business setup, and contract negotiation tips.',
  'operational_and_quality_management': 'The files cover operational compliance (environmental laws, food safety, ISO certification), quality control standards, disciplinary procedures, grievance handling, pest management (commercial farming/food processing), and hygiene guidelines for food businesses.',
  'financial_management_and_funding': 'This list is about handling money in a business. It covers things like cash flow, inventory costs, invoices, and loans. It also shows how to deal with banks and understand what your business owns and owes.',
  'agricultural_practices_and_guidelines': 'This list covers tips and methods for better farming, mostly dairy and livestock. It talks about cow and goat care, feeding, milking hygiene, heat stress, and choosing animals. It also includes info on biogas, hydroponics, tunnel farming, and mango export prep.',
  'marketinig_and_sales_guides': 'This list is all about marketing and sales. It covers how to sell better, find your target market, price your product, use social media, and build a brand. It also talks about online selling, customer service, SEO, and writing terms for online sales.',
  'general_business_operations_guides': 'This list covers how to run a business smoothly. It includes topics like handling crises, cyber security, HR, supply chain, logistics, imports/exports, business types, and outsourcing. It also touches on growth and planning for the future.',
  'general_economy_and_sme_sector': 'This list focuses on the SME sector in Pakistan. It covers topics like climate change, COVID-19 impact, floods, taxes, and informality. It also looks at SME contributions to the economy, investment chances, and women-led businesses.',
  'agriculture_and_food_sector_reports': 'This list covers reports on farming and food in Pakistan. It includes crops like rice, maize, olives, and fruits, plus livestock, dairy, poultry, and honey. It also talks about food processing, preservation, certifications, and small business ideas like mushroom or silk farming.',
  'manufacturing_and_industrial_sector_reports': 'This list covers different manufacturing and industrial sectors in Pakistan. It includes reports on textiles, leather, steel, cutlery, pharmaceuticals, EVs, mining, renewable energy, and more. It also touches on exports like sports goods, furniture, and surgical tools.',
  'retail_and_service_sector_reports_overviews': 'This list covers small retail and service businesses like book shops, garment stores, medical stores, auto repair, and mobile shops. It also includes services like travel agencies, courier, transport, photography, and electronics repair.',
  'financial_banking_and_corporate_legal_documents_non_agreement': 'This list has bank forms and company legal papers. It includes account opening forms, powers of attorney, declarations, promissory notes, and shareholder agreements. Also, theres stuff like privacy policy and fund use undertakings.',
  'insurance_documents': 'This list is about different types of insurance. It covers farming, building, goods under loan, assets you cant move, and guarantee insurance.',
  'transactional_and_order_forms_slips': 'This list has common business forms for buying and selling stuff—like bills of lading, packing slips, price quotes, purchase orders, invoices, and receipts.'
  }

FOLDER_DETAILS = ''
for key in TOPICS:
  FOLDER_DETAILS += f'Folders of topic {key}: '
  for folder in TOPICS[key]:
    FOLDER_DETAILS += f'{folder}, '
  FOLDER_DETAILS += '\n'

# print(FOLDER_DETAILS)